# Generated by Django 2.0 on 2018-07-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.AddField(
            model_name='resume',
            name='text',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
